name: Java CI with Maven & Release

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'

    - name: Update version in pom.xml
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        echo "Updating pom.xml version to $VERSION"
        mvn versions:set -DnewVersion=$VERSION -DgenerateBackupPoms=false
    - name: Commit and Push version change
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add pom.xml
        git commit -m "Update pom.xml version to ${GITHUB_REF_NAME#v} [skip ci]"
        git push origin HEAD:main
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Generate JavaDoc
      if: startsWith(github.ref, 'refs/tags/')
      run: mvn javadoc:javadoc

    - name: Package JavaDoc
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cd target/site
        zip -r ../../javadoc.zip apidocs/
        cd ../..
    - name: Create Custom Source Zip
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        zip -r project-source-${{ github.ref_name }}.zip . -x ".git/*" "target/*"

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          target/*.jar
          javadoc.zip
          project-source-*.zip
